### ISSUE TITLE
Call directly into ansible to run playbooks using API, do not use subprocess.

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#438] opened 2016-05-04 18:18 UTC
As part of this, gather `ansible_total_memory_mb` and hardcoded RAM values to clean up https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/provision/ansible/playbooks/install-couchbase-server-package.yml#L13

**Comment by sethrosetter** [comment] 2016-05-19 21:37
This looks like a good resource for doing this - https://serversforhackers.com/running-ansible-2-programmatically

**Comment by sethrosetter** [comment] 2016-05-19 21:53
Also here - https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/provision/ansible/playbooks/install-sync-gateway-package.yml#L33 and https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/provision/ansible/playbooks/install-sync-gateway-package.yml#L33

**Comment by tleyden** [comment] 2016-05-25 22:06
Running into something fairly bizarre .. in `ansible/plugins/strategy/linear.py`:

```
for host in hosts_left:
   if host in included_file._hosts:
       all_blocks[host].append(final_block)
   else:
       all_blocks[host].append(noop_block)
```

Even though `included_file._hosts` contained a list: `[sg1, sg2]`, and host is `sg1` (or `sg2`), it's not matching.

I changed the code to:

```
                                display.debug("iterating over hosts_left: {}".format(hosts_left))
                                for host in hosts_left:
                                    for host_inner in hosts_left:
                                        found_match = False
                                        if host == host_inner:
                                            display.debug("host {} == host_inner: {}".format(host, host_inner))
                                            all_blocks[host].append(final_block)
                                            found_match = True
                                        else:
                                            display.debug("host {} != host_inner: {}".format(host, host_inner))
                                        if not found_match:
                                            all_blocks[host].append(noop_block)
```

and it works.  Here's a gist of the output when it works:  https://gist.github.com/tleyden/c5c55e4d0697a84afb70a2950d714bbb

**Comment by tleyden** [comment] 2016-05-25 22:27
Ok I realized the "working" code had an error, it was looping over `hosts_left` rather than `included_file._hosts`

The problem is that for some reason the hosts in `included_file._hosts` have different UUIDS.

![screen shot 2016-05-25 at 3 27 08 pm](https://cloud.githubusercontent.com/assets/296876/15558196/2911f18c-228d-11e6-8c53-50b8bfca04f0.png)

**Comment by tleyden** [comment] 2016-05-26 22:34
Running into another issue .. not sure if it's related to the changes, but this test:

```
robot --loglevel DEBUG -b debug.txt -v PROVISION_CLUSTER:True -v SERVER_VERSION:4.1.0 -v SYNC_GATEWAY_VERSION:$SG_COMMIT -t "test bucket shadow low_revs limit" testsuites/syncgateway/functional/2sg_1cbs/
```

failed with this error:

```
	ValueFormatError: <Failed to decode bytes, Results=1, inner_cause=Test timeout 10 minutes exceeded., C Source=(src/convert.c,222), OBJ='{"channels":["ABC","NBC","CBS"],"updates":0}'>	
14:46:22.571	DEBUG	Traceback (most recent call last):
  File "/Users/tleyden/Development/mobile-testkit/testsuites/syncgateway/functional/test_bucket_shadow.py", line 158, in test_bucket_shadow_low_revs_limit
    get_doc_with_content_from_source_bucket_retry(doc_id, fake_doc_content, sc.source_bucket)
  File "/Users/tleyden/Development/mobile-testkit/testsuites/syncgateway/functional/test_bucket_shadow.py", line 263, in get_doc_with_content_from_source_bucket_retry
    doc = bucket.get(doc_id, quiet=True)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/couchbase/bucket.py", line 489, in get
    replica=replica, no_format=no_format)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 294, in loads
    def loads(s, encoding=None, cls=None, object_hook=None, parse_float=None,
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/robot/running/timeouts/posix.py", line 38, in _raise_timeout_error
    raise TimeoutError(self._error)
```

**Comment by sethrosetter** [comment] 2016-05-26 23:17
@tleyden, looks like the test is timing out. Did you verify the test is being setup properly? If the timeout is due to an invalid test environment (i.e. wrong sg config or something similar), it is probably due to the provisioning changes. Otherwise, it may be a bug.

**Comment by tleyden** [comment] 2016-05-26 23:43
Another [sporadic failure](http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/83/robot/report/) that seems to be similar:

```
TASK [wait until sync gateway to listen on port] *******************************
fatal: [sg1]: FAILED! => {"changed": false, "elapsed": 120, "failed": true, "msg": "Timeout when waiting for 127.0.0.1:4985"}
fatal: [sg2]: FAILED! => {"changed": false, "elapsed": 120, "failed": true, "msg": "Timeout when waiting for 127.0.0.1:4985"}

PLAY RECAP *********************************************************************
sg1                        : ok=7    changed=2    unreachable=0    failed=1   
sg2                        : ok=7    changed=2    unreachable=0    failed=1	
16:35:32.935	FAIL	Failed to start to Sync Gateway	
16:35:32.935	DEBUG	Traceback (most recent call last):
  File "/var/jenkins/workspace/syncgateway-functional-tests-dev/mobile-testkit/testsuites/syncgateway/functional/test_sg_replicate.py", line 290, in test_stop_replication_via_replication_id
    sg1, sg2 = create_sync_gateways(DEFAULT_CONFIG_PATH)
  File "/var/jenkins/workspace/syncgateway-functional-tests-dev/mobile-testkit/testsuites/syncgateway/functional/test_sg_replicate.py", line 335, in create_sync_gateways
    cluster.reset(config_path=config_path)
  File "/var/jenkins/workspace/syncgateway-functional-tests-dev/mobile-testkit/libraries/testkit/cluster.py", line 131, in reset
    assert status == 0, "Failed to start to Sync Gateway"
```

**Comment by sethrosetter** [comment] 2016-05-26 23:45
I would be willing to bet that it is due to https://github.com/couchbase/sync_gateway/issues/1745

**Comment by tleyden** [comment] 2016-06-01 17:05
Fixed via https://github.com/couchbaselabs/mobile-testkit/pull/490

**Closed by tleyden** 2016-06-01 17:05 UTC
