### ISSUE TITLE
Performance scenario: Replication with insert/update ratio

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#610] opened 2016-08-04 21:47 UTC
Currently gateload is 100% insert - no updates to existing docs.  Need a similar scenario that has a config lever to define the insert/update ratio.

**Comment by adamcfraser** [comment] 2016-08-12 18:51
1. Validate that locust can do the type of changes latency testing we need: write a doc, wait for it to arrive on changes, publish timing data.  Initial approach could match gateload - write a doc where the docid represents a timestamp, wait for that doc to show up in changes, calculate diff and report.  Eventually may need to move this to a property in the doc itself, if we want to be able to test update as well as insert.
2. Simulate full replication (bulk_docs, changes, bulk_get).  
3. Add levers for insert/update ratio.

**Comment by sethrosetter** [comment] 2016-08-16 21:20
@adamcfraser Do we need levers for num channels?

**Comment by adamcfraser** [comment] 2016-08-19 17:57
Probably want something equivalent to gateload eventually - so you can specify number of channels used, and by extension users/channel.  I think it's easier to understand if you just take 'number of channels' as a test parameter (instead of the gateload approach, which is users/channel).

**Comment by tleyden** [comment] 2016-08-23 21:50
Caught up w/ @sethrosetter and some awkward issues observed w/ locust are:

1. Locust is emitting errors whenever a locust dies, which makes the logs hard to interpret
1. No clean way to pass parameters down to scenario except for setting raw environment variables on the command line, which means that it's necessary to write wrapper scripts
1. Had to add a lot of code that would be expected to work out of the box
  1. Code to wait for everything to hatch

Action items:

- [ ] FIX: Locust is emitting errors whenever a locust dies, which makes the logs hard to interpret

**Comment by tleyden** [comment] 2016-09-21 19:03
Closing as duplicate of https://github.com/couchbaselabs/mobile-testkit/issues/675

**Closed by tleyden** 2016-09-21 19:03 UTC
Labels: in progress, performance, scenario
