### ISSUE TITLE
Winning revs race

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1136] opened 2017-04-19 16:48 UTC
http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/468/testReport/junit/testsuites.syncgateway.functional.tests/test_conflicts/test_winning_conflict_branch_revisions_sync_gateway_default_functional_tests_/

**Comment by raghusarangapani** [comment] 2017-04-24 19:22
Duplicate of https://github.com/couchbaselabs/mobile-testkit/issues/962

**Closed by raghusarangapani** 2017-04-24 19:22 UTC
Labels: intermittent-failure, P1: high, ready
