### ISSUE TITLE
Investigate hanging test

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#950] opened 2017-02-14 18:49 UTC
Run The same configuration as this job  - http://uberjenkins.sc.couchbase.com/job/listener-client-client/27/

The test (test_peer_2_peer_sanity) hung for 9 hours. I'm guessing it is a deadlock scenario. 

Please try to repro in a loop.

**Comment by raghusarangapani** [comment] 2017-02-20 18:27
I am unable to reproduce this issue, Closing it after discussing it with Seth

**Closed by raghusarangapani** 2017-02-20 18:27 UTC
Labels: P1: high, ready
