### ISSUE TITLE
Publish sync gateway logs when tests fail

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#436] opened 2016-05-04 17:55 UTC
Instead of:

```
KEYWORD LoggingKeywords . Fetch And Analyze Logs
Start / End / Elapsed:	20160504 10:05:44.977 / 20160504 10:05:46.444 / 00:00:01.467
10:05:44.978	ERROR	
!!!!!!!!!! TEST FAILURE !!!!!!!!!!	
10:05:46.443	INFO	Pulling logs
sync_gateway logs copied here /tmp/TEST-FAILURE-2016-05-04-10-05-46-sglogs
```

just attach log to jenkins job as artifact like debug.txt

**Comment by sethrosetter** [comment] 2016-06-10 18:45
Closing as dupe of #75

**Closed** 2016-06-10 18:45 UTC
Labels: icebox
